table br_mobilidados_indicadores_taxa_motorizacao
	lineageTag: 9c2f74da-c5c7-4144-8c5b-53dd2f27bf50

	column ano
		dataType: int64
		formatString: 0
		lineageTag: d812f598-43a1-4f31-bb0b-4f43a5d61a62
		summarizeBy: sum
		sourceColumn: ano

		annotation SummarizationSetBy = Automatic

	column sigla_uf
		dataType: string
		lineageTag: 63a9d887-47eb-4443-bda2-07120a76d3e2
		summarizeBy: none
		sourceColumn: sigla_uf

		annotation SummarizationSetBy = Automatic

	column id_municipio
		dataType: int64
		formatString: 0
		lineageTag: b2ff2471-0500-4d51-b3d3-231d3b7f45c8
		summarizeBy: none
		sourceColumn: id_municipio

		annotation SummarizationSetBy = Automatic

	column taxa_motorizacao
		dataType: int64
		formatString: 0
		lineageTag: 9389cd8b-48bd-489b-ba3e-3eec77410304
		summarizeBy: sum
		sourceColumn: taxa_motorizacao

		annotation SummarizationSetBy = Automatic

	partition br_mobilidados_indicadores_taxa_motorizacao = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("I:\.shortcut-targets-by-id\16mpUODAKcXBWhSgDliFa5sVdzSAlQTCg\Grupo de Estudos Dados\Projeto\dataset\br_mobilidados_indicadores_taxa_motorizacao.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ano", Int64.Type}, {"sigla_uf", type text}, {"id_municipio", Int64.Type}, {"taxa_motorizacao", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

