table br_mobilidados_indicadores_proporcao_pessoas_prox_infra_cicloviaria
	lineageTag: 90670b76-ad4b-4757-863a-77605031707a

	column ano
		dataType: int64
		formatString: 0
		lineageTag: 8984eaad-0840-4710-ac68-4bd7d0b64a0b
		summarizeBy: sum
		sourceColumn: ano

		annotation SummarizationSetBy = Automatic

	column sigla_uf
		dataType: string
		lineageTag: 44f0f488-695a-4d3d-804a-093142c36ac2
		summarizeBy: none
		sourceColumn: sigla_uf

		annotation SummarizationSetBy = Automatic

	column id_municipio
		dataType: int64
		formatString: 0
		lineageTag: 31cc12d9-7eb8-49fb-9aec-0ab29c7a379c
		summarizeBy: sum
		sourceColumn: id_municipio

		annotation SummarizationSetBy = Automatic

	column indicador
		dataType: string
		lineageTag: cf3c8872-0851-4599-9498-fdcce92bba38
		summarizeBy: none
		sourceColumn: indicador

		annotation SummarizationSetBy = Automatic

	column prop_pessoas_proximas_ciclovias
		dataType: int64
		formatString: 0
		lineageTag: e4ef9929-dff4-43a6-98d7-ab9f4eeb326c
		summarizeBy: sum
		sourceColumn: prop_pessoas_proximas_ciclovias

		annotation SummarizationSetBy = Automatic

	partition br_mobilidados_indicadores_proporcao_pessoas_prox_infra_cicloviaria = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("I:\.shortcut-targets-by-id\16mpUODAKcXBWhSgDliFa5sVdzSAlQTCg\Grupo de Estudos Dados\Projeto\dataset\br_mobilidados_indicadores_proporcao_pessoas_prox_infra_cicloviaria.csv"),[Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ano", Int64.Type}, {"sigla_uf", type text}, {"id_municipio", Int64.Type}, {"indicador", type text}, {"prop_pessoas_proximas_ciclovias", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

