table br_mobilidados_indicadores_divisao_modal
	lineageTag: 69fdefb7-1f85-44f2-a62b-2125cb3fd44a

	column ano
		dataType: int64
		formatString: 0
		lineageTag: 2963e9c1-c5af-4537-a914-300a793e59d0
		summarizeBy: sum
		sourceColumn: ano

		annotation SummarizationSetBy = Automatic

	column sigla_uf
		dataType: string
		lineageTag: 5e8caf6d-e4b1-4101-872a-7b5b47e3a7c7
		summarizeBy: none
		sourceColumn: sigla_uf

		annotation SummarizationSetBy = Automatic

	column coluna
		dataType: string
		lineageTag: 49ff6f91-c8ee-4d11-af0e-97d5e053c4ef
		summarizeBy: none
		sourceColumn: coluna

		annotation SummarizationSetBy = Automatic

	column divisao_modal
		dataType: double
		lineageTag: 7409fd2e-3566-4e8a-993a-10fd6fe445ad
		summarizeBy: sum
		sourceColumn: divisao_modal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition br_mobilidados_indicadores_divisao_modal = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\Nitro5\OneDrive\Documentos\GitHub\grupo-dados\dataset\original\br_mobilidados_indicadores_divisao_modal.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ano", Int64.Type}, {"sigla_uf", type text}, {"coluna", type text}, {"divisao_modal", type number}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

