table br_mobilidados_indicadores_proporcao_pessoas_proximas_pnt
	lineageTag: dfe8376b-fc8a-465f-88d3-6f3da48d88a2

	column ano
		dataType: int64
		formatString: 0
		lineageTag: f6d6244f-4a3f-4c9e-82dc-695745cf8040
		summarizeBy: sum
		sourceColumn: ano

		annotation SummarizationSetBy = Automatic

	column sigla_uf
		dataType: string
		lineageTag: 610aa403-543d-427d-8c87-0ad27e3c7391
		summarizeBy: none
		sourceColumn: sigla_uf

		annotation SummarizationSetBy = Automatic

	column id_municipio
		dataType: int64
		formatString: 0
		lineageTag: 6408efc6-c2a3-4068-bebb-22f41a09f460
		summarizeBy: none
		sourceColumn: id_municipio

		annotation SummarizationSetBy = Automatic

	column indicador
		dataType: string
		lineageTag: 44d78e29-e2e8-433d-9de5-0463f0e50b00
		summarizeBy: none
		sourceColumn: indicador

		annotation SummarizationSetBy = Automatic

	column prop_pessoas_proximas_pnt
		dataType: int64
		formatString: 0
		lineageTag: 583dcd05-7297-4632-b97d-a942eb1f53af
		summarizeBy: sum
		sourceColumn: prop_pessoas_proximas_pnt

		annotation SummarizationSetBy = Automatic

	partition br_mobilidados_indicadores_proporcao_pessoas_proximas_pnt = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("I:\.shortcut-targets-by-id\16mpUODAKcXBWhSgDliFa5sVdzSAlQTCg\Grupo de Estudos Dados\Projeto\dataset\br_mobilidados_indicadores_proporcao_pessoas_proximas_pnt.csv"),[Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ano", Int64.Type}, {"sigla_uf", type text}, {"id_municipio", Int64.Type}, {"indicador", type text}, {"prop_pessoas_proximas_pnt", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

