table infra_domicilios_urbana
	lineageTag: 6d1f1b3d-f4f4-4968-ad99-aeaef2b34019

	column ano
		dataType: int64
		formatString: 0
		lineageTag: e144e8ed-22a6-4428-aa26-2fcfddd7d43c
		summarizeBy: sum
		sourceColumn: ano

		annotation SummarizationSetBy = Automatic

	column sigla_uf
		dataType: string
		lineageTag: 96f4c51e-9a6b-47a1-8a80-7a07322ae12b
		summarizeBy: none
		sourceColumn: sigla_uf

		annotation SummarizationSetBy = Automatic

	column id_municipio
		dataType: int64
		formatString: 0
		lineageTag: 49d9f97e-5532-490c-8d87-a7af24dcfd3f
		summarizeBy: none
		sourceColumn: id_municipio

		annotation SummarizationSetBy = Automatic

	column prop_calcadas
		dataType: int64
		formatString: 0
		lineageTag: c8302d86-4285-4464-bac8-5accd49c87c6
		summarizeBy: sum
		sourceColumn: prop_calcadas

		annotation SummarizationSetBy = Automatic

	column prop_rampas
		dataType: int64
		formatString: 0
		lineageTag: eb327e0f-224a-4f02-86d8-234a93de2069
		summarizeBy: sum
		sourceColumn: prop_rampas

		annotation SummarizationSetBy = Automatic

	partition infra_domicilios_urbana = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("I:\.shortcut-targets-by-id\16mpUODAKcXBWhSgDliFa5sVdzSAlQTCg\Grupo de Estudos Dados\Projeto\dataset\br_mobilidados_indicadores_proporcao_domicilios_infra_urbana.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ano", Int64.Type}, {"sigla_uf", type text}, {"id_municipio", Int64.Type}, {"prop_calcadas", Int64.Type}, {"prop_rampas", Int64.Type}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Tipo Alterado")
				in
				    #"Duplicatas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

