table tempo_deslocamento
	lineageTag: adb24fed-2ab1-4b9d-abdf-3657e6bf1271

	column ano
		dataType: int64
		formatString: 0
		lineageTag: 0d3d6896-de71-41b7-8f8c-280a45176618
		summarizeBy: sum
		sourceColumn: ano

		annotation SummarizationSetBy = Automatic

	column sigla_uf
		dataType: string
		lineageTag: 00e1dcd6-8771-4844-a2da-5bfa820b8006
		summarizeBy: none
		sourceColumn: sigla_uf

		annotation SummarizationSetBy = Automatic

	column id_municipio
		dataType: int64
		formatString: 0
		lineageTag: 4195e965-50a6-4464-a960-62b26d9666c5
		summarizeBy: none
		sourceColumn: id_municipio

		annotation SummarizationSetBy = Automatic

	column tempo_medio_deslocamento
		dataType: int64
		formatString: 0
		lineageTag: c80f2e92-ca50-4c6e-b6b9-18aab6770a1b
		summarizeBy: sum
		sourceColumn: tempo_medio_deslocamento

		annotation SummarizationSetBy = Automatic

	column prop_deslocamento_acima_1_hora
		dataType: int64
		formatString: 0
		lineageTag: 7c95e9ee-1ba4-4ed6-a363-1a156a37f802
		summarizeBy: sum
		sourceColumn: prop_deslocamento_acima_1_hora

		annotation SummarizationSetBy = Automatic

	partition tempo_deslocamento = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("I:\.shortcut-targets-by-id\16mpUODAKcXBWhSgDliFa5sVdzSAlQTCg\Grupo de Estudos Dados\Projeto\dataset\br_mobilidados_indicadores_tempo_deslocamento_casa_trabalho.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ano", Int64.Type}, {"sigla_uf", type text}, {"id_municipio", Int64.Type}, {"tempo_medio_deslocamento", Int64.Type}, {"prop_deslocamento_acima_1_hora", Int64.Type}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Tipo Alterado")
				in
				    #"Duplicatas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

